apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-old
  labels:
    app: nginx-old
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-old
  template:
    metadata:
      labels:
        app: nginx-old
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80